name: Delövning 3 - Artifacts

on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Skapar log.txt
        run: echo  "Hello world 123" > log.txt # 1. skapa filen
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # 2a. vilken action kan användas här? 
        with:
          name: loggfil
          path: log.txt