name: Delövning 4 - Triggers

on:
  push:
  # 1. trigga på commit
  # 2. trigga på pull request
  pull_request:
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo info        
        run: echo "Workflow triggat av pull request med merge" # TODO: uppdatera texten